Fixed casting warning (Uint64 to size_t). Error in build: d:\visualprojects\musicequaliser\sfml-2.5.1\include\sfml\graphics\rect.inl(81): error C2589: '(': illegal token on right side of '::'. Cause of error unknown.